name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build on &{{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-command: |
              "yarn oclif pack tarballs"
              "yarn oclif pack deb"
          - os: windows-latest
            build-command: 'yarn oclif pack win'
          - os: macos-latest
            build-command: 'yarn oclif pack macos'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.4.0'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn lint
          yarn test
          yarn build
          yarn prepack
          ${{ matrix.build-command }}
          yarn posttest
          yarn postpack

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/**/*.exe
            dist/**/*.pkg
            dist/**/*.deb
            dist/**/*.tar.xz
            dist/**/*.tar.gz
